# Introduction
State notebook purpose here

### Imports
Import libraries and write settings here.

In [1]:
# Data manipulation
import pandas as pd
import numpy as np

# Options for pandas
pd.options.display.max_columns = 50
pd.options.display.max_rows = 30

# Display all cell outputs
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

from IPython import get_ipython
ipython = get_ipython()

# autoreload extension
if 'autoreload' not in ipython.extension_manager.loaded:
    %load_ext autoreload

%autoreload 2

# Visualizations
import plotly.plotly as py
import plotly.graph_objs as go
from plotly.offline import iplot, init_notebook_mode
init_notebook_mode(connected=True)

import cufflinks as cf
cf.go_offline(connected=True)
cf.set_config_file(theme='white')

In [5]:
data = pd.read_csv('/Users/jagoodka/Dropbox/Jagoda/my_github/DataScience/housing/housing.csv')
data.sample(10)
data.info()
data['ocean_proximity_cat'] = data['ocean_proximity'].factorize()[0]
# each row represents one district

,Unnamed: 0,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,ocean_proximity_cat
995,995,-121.75,37.71,11.0,12070.0,2220.0,5826.0,2125.0,4.8624,192400.0,INLAND,2
8377,8377,-118.35,33.95,30.0,2661.0,765.0,2324.0,724.0,3.0519,137500.0,<1H OCEAN,1
10250,10250,-117.86,33.88,19.0,1621.0,328.0,871.0,322.0,3.7361,201400.0,<1H OCEAN,1
11378,11378,-117.95,33.69,26.0,1417.0,264.0,817.0,261.0,4.8750,230400.0,<1H OCEAN,1
18494,18494,-121.57,37.02,17.0,2889.0,624.0,2681.0,608.0,2.9417,178000.0,INLAND,2
2632,2632,-124.18,40.62,35.0,952.0,178.0,480.0,179.0,3.0536,107000.0,NEAR OCEAN,3
4748,4748,-118.35,34.05,52.0,1971.0,414.0,1065.0,409.0,3.6435,195800.0,<1H OCEAN,1
4706,4706,-118.34,34.06,52.0,1482.0,336.0,768.0,300.0,3.7167,327300.0,<1H OCEAN,1
7646,7646,-118.27,33.81,42.0,865.0,208.0,811.0,218.0,3.8621,165300.0,<1H OCEAN,1
18430,18430,-121.87,37.26,24.0,2383.0,343.0,1146.0,341.0,5.6223,265700.0,<1H OCEAN,1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 12 columns):
Unnamed: 0             20640 non-null int64
longitude              20640 non-null float64
latitude               20640 non-null float64
housing_median_age     20640 non-null float64
total_rooms            20640 non-null float64
total_bedrooms         20433 non-null float64
population             20640 non-null float64
households             20640 non-null float64
median_income          20640 non-null float64
median_house_value     20640 non-null float64
ocean_proximity        20640 non-null object
ocean_proximity_cat    20640 non-null int64
dtypes: float64(9), int64(2), object(1)
memory usage: 1.9+ MB

In [10]:
feats = ['total_rooms', 'housing_median_age']

# Results
Show graphs and stats here

# Conclusions and Next Steps
Summarize findings here